### ISSUE TITLE
求训练好的模型权重谢谢！

### ISSUE THREAD

**Issue by HarrisonC7** [homxxx/MicroExpressionRecognition#16]
297541882@qq.com 感谢！

**Comment by m0urner** [comment]
借楼 2182601504@qq.com 感谢！

**Comment by wuchenyue** [comment]
借楼 2321546977@qq.com 非常感谢！

**Comment by maybwill** [comment]
借楼793182834@qq.com非常感谢🙏🏻

**Comment by WeiDai-David** [comment]
944899059@qq.com thanks

**Comment by HQwilbur** [comment]
同求权重参数文件，2489487038@qq.com，谢谢

**Comment by Zeiwoos** [comment]
2872122367@qq.com Thanks!😘

**Comment by zms-user** [comment]
您好，同求权重参数文件，谢谢。zhangmaosen23@gmail.com

**Comment by ny-xyt** [comment]
借楼 3439640879@qq.com 感谢！

**Comment by Frankslol** [comment]
借楼1207703232@qq.com非常感谢！！

**Comment by Paras-Shah-sudo** [comment]
Hello can I please get the training weights? You can send it on my gmail: paras178a@gmail.com Thanks
